pik-piam/gms

.buildlibrary, .zenodo.json, DESCRIPTION, R/update_modules_embedding.R, README.md
This is a suggestion to fix an issue identified running remind.
If you were working on a new module realization in remind git repository, but then switched to a different branch, sometimes the folder is not deleted because untracked input files are present. In this case, remind fails announcing in its `log.txt`:
```
Error in replace_in_file(realizationGMSpath, code, subject = "PHASES") : 
File ./modules/45_carbonprice/NDC_linreg/realization.gms does not exist!
Calls: prepare -> update_modules_embedding -> replace_in_file
```
In this PR, I suggest to then simply issue a warning, but not let the model run fail. Of course, it will fail later if you actually tried to use the non-existing realization.
=> if module realization file not exists, issue warning instead of stopping

.buildlibrary, .zenodo.json, DESCRIPTION, R/update_modules_embedding.R, README.md, gms.Rproj, man/update_modules_embedding.Rd
In #10, I fixed that if a module realization does not exist, it warns instead of breaking the model.
This PR extends that to non-existing modules in folders, which can also happen if you check out a git branch where this module does not exist, but the folder is kept because of input files.
I first look for all the modules (now with getModules()) and construct the path to the corresponding gms file. If this file doesn't exist, these modules are sorted out.
I further cleaned the code. It uses less nested for-loops and more paste on vectors. Instead of running through the list of modules twice, I only walk through once.
I tested it by adding empty or non-empty module folders and realizations, it seems to work well.
=> similar to PR10, allow for empty module folders

.buildlibrary, .zenodo.json, DESCRIPTION, R/check_config.R, R/setScenario.R, README.md, tests/testthat/test-checkConfig.R
`check_config` has the option to add `extras`, a vector with additional arguments that are allowed in the cfg. Unfortunately, it was impossible to specify something like `gms$addsomething` as extra, because the checking routing forgets everything after the `$`, see below, `cfg$gms$addsomething` cannot be catched, only if `gms` is added to `extras`, resulting in a not very specific exclusion.
```
cfg <- list(title = "default", gms = list(switch1 = TRUE, switch2 = 1, fancymodule = "default", crazymodule = "simple"))
cfgextra <- list(title = "default", gms = list(switch1 = TRUE, switch2 = 1, fancymodule = "default", crazymodule = "simple", extra1 = TRUE), extra2 = TRUE)
check_config(cfgextra, reference_file = cfg, modulepath = system.file("dummymodel/modules/", package="gms"), extras = …
```
=> in check_config, enable to add extras such as gms$c_expname

.buildlibrary, .zenodo.json, DESCRIPTION, R/singleGAMSfile.R, README.md, inst/dummymodel/main.gms, inst/dummymodel/modules/03_Rmodule/module.gms, inst/dummymodel/modules/03_Rmodule/withr/calculations.gms, inst/dummymodel/modules/03_Rmodule/withr/realization.gms, inst/dummymodel/modules/03_Rmodule/withr/run_calculations.R, inst/dummymodel/modules/include.gms, inst/extdata/full.gms, inst/extdata/full_embed.gms, man/singleGAMSfile.Rd, tests/testthat/test-checkConfig.R, tests/testthat/test-singleGAMSfile.R
Hi,
This adds an option to singleGAMSfile to also embed R scripts which are executed using
```gams
Execute "Rscript path/to/script.R";
```
in GAMS. This will be transformed into
```gams
$onecho > script.R
<content of script.R>
$offecho
Execute "Rscript script.R";
```
The transformation is not enabled by default but gated behind a boolean flag argument so that users can choose themselves to enable the transformation.
Cheers,
Mika
=> singleGAMSfile: add option to also embed executed R scripts

.buildlibrary, .github/workflows/lucode2-check.yaml, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, R/getLine.R, README.md
When we moved `getLine` from all over our codebase to gms, we also deleted the `if (interactive)` block because it didn't seem like we needed it, everything was working interactively nicely when using `R` or `radian`. However, it turns out jupyter and RStudio do even more funky stuff with stdin, and it doesn't work. So, fall back to `readline()` in interactive use again. `readline()` is so frequently used, it should work in all fancy interactive environments.
Fixes: #31
=> Fix getLine() in RStudio

.buildlibrary, .github/workflows/lucode2-check.yaml, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, R/codeCheck.R, R/selectScript.R, README.md, man/codeCheck.Rd
Hi,
There was a name clash in `codeCheck` between the index variable in a for loop and the more or less global warnings vector, both named `w`. Maybe a cautionary tale about one-character variable names?
Anyway, lucode2 decided that because I fixed this name clash, I should also completely refactor `codeCheck` to make the linter happy. And who am I to disagree? The linter is not yet fully happy now, but at least it is a lot happier. There are still a couple functions to be extracted out of the big block of code, and some other weird things to fix, but I think it is less intimidating now. And a lot is simply not fixable without changing the API, like the shadowing of the global name `debug`.
Additionally, I found one more `getLine` that can go away.
I tested this by throwing it at a REMIND …
=> Fix name clash and refactor codeCheck

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, R/interfaceplot.R, README.md
Being a good employee I keep my packages up-to-date, which lead to
```
== Warnings ====================================================================
1. interfaceplot creation works (test-interfaceplot.R:13) - Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `"from"` instead of `.data$from`
2. interfaceplot creation works (test-interfaceplot.R:13) - Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
ℹ Please use `"to"` instead of `.data$to`
```
Now it does
```
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```
=> fix select() syntax deprecated in tidyselect 1.2.0

.buildlibrary, .zenodo.json, DESCRIPTION, R/download_distribute.R, R/download_unpack.R, R/interfaceplot.R, README.md
Currently, if any of the files that `download_distribute()` is to process are missing, it will tell the user so, e.g.
```
Following files not found:
rev6.316_62eff8f7_remind.tgz
rev6.316_62eff8f7_validationremind.tgz
```
just to continue with lots of
```
f_maxProdGradeRegiWindOff.cs3r                                                                                            ->  FAILED!
pm_histCap_windoff.cs3r                                                                                                   ->  FAILED!
p_histCapFac_windoff.cs4r                                                                                                 ->  FAILED!
```
flushing the interesting information way past what the user can see.
With this patch, the argument `stopOnMissing` is passed from …
=> add option to stop download_distribute() if files are missing

.buildlibrary, .zenodo.json, DESCRIPTION, R/codeCheck.R, README.md, man/codeCheck.Rd, tests/testthat/test-codeCheck.R
Hi,
The given `reason` used to be `questionnaire`, now it is `added by codeCheck`, which is more self-explanatory, I hope.
Also, I added more `nolints` to things that the linter doesn't like which we won't fix. Also, I renamed the parameter `debug` to `returnDebug`, which is an API change, but:
* the parameter is not used throughout the pik-piam universe (searched via `reposearch`)
* it is only meant to be used interactively and seldom, so hopefully nobodies workflows will be broken.
* keeping the parameter name not only scares the linter, but also breaks actual debugging via `debug()`, so I think renaming makes proper debugging *easier*.
Cheers
Mika
=> Use a self-explanatory reason when adding to not_used.txt

.buildlibrary, .zenodo.json, DESCRIPTION, Makefile, R/checkNoTabs.R, README.md, man/checkAppearance.Rd, man/checkNoTabs.Rd, man/interfaceplot.Rd, man/is.modularGAMS.Rd, man/module.skeleton.Rd, man/update_modules_embedding.Rd, man/writeSets.Rd, tests/testthat/test-checkNoTabs.R
checkNoTabs took 2min on the cluster, mostly because it was unnecessarily going through lots of folders (`list.files`). This PR allows pre filtering folders which leads to ~5sec runtime on the cluster in a magpie folder.
=> improve performance of checkNoTabs

tests/testthat/test-checkNoTabs.R
This should fix the problem [here](https://github.com/r-universe/pik-piam/actions/runs/4204456869/jobs/7370956673), the test was assuming `/` where Windows used `\`.
=> fix checkNoTabs test for windows

.buildlibrary, .zenodo.json, DESCRIPTION, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
https://github.com/pik-piam/gms/pull/58 broke the case where the input is not grouped at all, and unfortunately, the tests didn't catch it. This breaks e.g. `rs2`.
I added a test for this and fixed it.
=> Fix chooseFromList for no groups at all

.buildlibrary, CITATION.cff, DESCRIPTION, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
- if your list is long and you want to select a pattern, it is sometimes tedious to type the number 483 to select a pattern.
- Now, you can type `a` for `all` and `p` for `pattern`
- Also improve the error message by appending the fail message
=> accept a=all and p=pattern in chooseFromList

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, Makefile, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
- chooseFromList always had a mode for using regular expressions
- that is extremely annoying if you want to select AR6 / remind2 variables that contain several `|`
- add fixed=TRUE mode so that user can decide whether that pattern should _not_ be interpreted as regular expression
=> add fixed=TRUE pattern mode to chooseFromList

.buildlibrary, CITATION.cff, DESCRIPTION, R/chooseFromList.R, README.md
- In #64 I introduced a bug if `chooseFromList` was called with `multiple = FALSE` and `addAllPattern = TRUE`, the latter being the standard setting. Obviously, it makes no sense to select "all" if you are not allowed to select multiple, so I set `addAllPattern` to `FALSE` if `multiple` is `FALSE`
- the lower lines are just sorting…
- That is how it looked like:
```
Please choose slurm mode:
That was the mess it created:
1,a: priority
2: short
3: standby
4: priority mem=8000
5: short mem=8000
6: standby mem=8000
7: priority mem=32000
8: direct
1: priority
2,p: short
3,f: standby
Uses the first option if empty.
Number or leave empty:
```
=> chooseFromList: don't allow multiple=FALSE, addAllPattern=TRUE

.buildlibrary, CITATION.cff, DESCRIPTION, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
- in #64, I introduces some bugs that needed fixing in #65 and #66. Make sure that does not happen again.
- chooseFromList is quite generous with errors and let the user try as often as he likes to get it right. The test now mocks `getLine` to `stop()` and so if the user is asked again, that results in an error that the tests can catch.
=> add better tests to chooseFromList

.buildlibrary, .github/workflows/check.yaml, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
1. `chooseFromList(NULL)` or `chooseFromList(list())` now directly returns the empty list instead of this nonsense where you cannot actually select anything meaningful:
```
Please choose runs to be used for output generation:
1,a: all
2,p: Search pattern by regular expression...
3,f: Search by fixed pattern...
```
2. I use the `with_mocked_bindings` binding `getLine` to `stop()` or some specific value now everywhere in chooseFromList tests to avoid that the script hangs on such a call instead of failing. The only substantive change in the test script is adding:
```
zerolength <- list(NULL, logical(0), character(0), numeric(0), list(), a = NULL)
for (z in zerolength) {
expect_identical(chooseFromList(z), z)
expect_message(chooseFromList(z), "returning the empty list")
}
```
=> if chooseFromList gets empty list, just return it

.buildlibrary, CITATION.cff, DESCRIPTION, R/download_distribute.R, R/getfiledestinations.R, README.md
- `getfiledestination` now returns NULL if no `files` file is found
- Before, it threw a meaningless error message.
- `download_distribute` can now handle a NULL from `getfiledestination` and will download and unpack but not distribute in this case
- It gives a message to let the user know that there is no distribution of files.
- This allows to use the function also when no distribution is wanted (like in BRICK, potentially EDGE-T).
=> Make file distribution optional and better error message

.buildlibrary, CITATION.cff, DESCRIPTION, R/model_lock.R, README.md
old:
```
2023-09-29 22:09:37: acquiring model lock...
acquired model lock in 3.9 secs.
```
new:
```
2023-09-29 22:09:37: try to acquire model lock...
2023-09-29 22:09:41: acquired model lock in 3.9 secs.
```
=> Improve log messages for model_lock

.buildlibrary, .github/workflows/check.yaml, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, README.md, inst/dummymodel/main.gms, inst/dummymodel/modules/02_crazymodule/complex/realization.gms, inst/extdata/full.gms, inst/extdata/full_embed.gms, man/gms-package.Rd
The dummy model is extended to use the extrapage attribute, so it can be included in the unit tests of https://github.com/pik-piam/goxygen/pull/22
=> add extrapage attribute to dummy model

.buildlibrary, CITATION.cff, DESCRIPTION, R/getfiledestinations.R, README.md
I am doing REMIND runs with differing input data and noticed `getfiledestinations()` being glacially slow – runs would seemingly stall for 15 to 20 minutes before loading input data.  The problem is that I have a directory with old runs (54 runs with 72k files total) that makes `list.files(recursive = TRUE)` question its life choices.
-----
`getfiledestinations()` used to ignore everything starting with `.`, `225`, `output`, `calib_run`, `figure`.
Now, it ignores
- anything starting with `.`,
- on MAgPIE: `calib_run`, `input`, `output`, `doc`, `run_details`, `logs`, `225.*`,
- on REMIND: `input`, `output`, `doc`, `magpie`, `plotRuntimeDependencies`, `\\.venv`, `calibration_results`,
- and anything else included included in `.gitignore`.
=> have getfiledestinations() ignore directories from .gitignore

.buildlibrary, CITATION.cff, DESCRIPTION, R/update_modules_embedding.R, README.md, tests/testthat/test-update_modules_embedding.R
- if a realization is deleted in the repo, often the `input` folder remains in the clones, containing the input files that are not version-controlled
- `update_modules_embedding` then adds that empty realization to `module.gms`, but warns it cannot be used
- After this PR: Warn that it cannot be used, and therefore don't add it to `module.gms`
- added a small test that let me find several errors:
- `modelpath` was not used consistently, often assuming `.`
- if the first line of `main.gms` contains an include, the script ran infinitely
=> don't add empty realizations to main module files

.buildlibrary, CITATION.cff, DESCRIPTION, R/getfiledestinations.R, README.md, man/getfiledestinations.Rd
- to be able to run it with `gms::getfiledestinations(path = "../..")` in the tests
=> add 'path' param to getfiledestinations

.buildlibrary, CITATION.cff, DESCRIPTION, R/codeCheck.R, README.md
- Adjust not_used.txt files only in `interactive = TRUE` mode
- Avoid that the interactive scripts wants to add things that were never declared to many not_used.txt -> close https://github.com/pik-piam/gms/issues/68
- Improve warnings in this case
- it is recommended to compare files with whitespace = 1 mode: https://github.com/pik-piam/gms/pull/92/files?w=1
What happens if you add `cm_NDC_version`, which is a switch name but has no GAMS definition, to `modules/46_carbonpriceRegi/netZero/not_used.txt` in remindmodel? 
In the following, irrelevant stuff shortened with `[...]`:
Old with `interactive = FALSE`. While the first warning makes sense, the three others are completely misleading.
```
Running codeCheck...
[...]
Switch Appearance check done...        (time elapsed:  70.92)
Interface …
```
=> codeCheck: edit not_used.txt only if interactive; auto-remove stuff never declared

.buildlibrary, CITATION.cff, DESCRIPTION, R/readDeclarations.R, README.md
Consider this GAMS code
```
Parameter
f_foo(x)   "description"
/
$$ondelim
$$include "./some/file/to/read.csv";
$$offdelim
/
;
```
for which `codeCheck()` reports
```
codeCheck reported code inconsistencies. Please fix the given warnings!
Warning messages:
1: "$$ondelim" does not follow the given naming conventions (description = "")! 
2: "$$include" does not follow the given naming conventions (description = "./some/file/to/read.csv")!
```
Better to filter $$-expressions, too.
=> remove $$-expressions from declarations

.buildlibrary, CITATION.cff, DESCRIPTION, R/chooseFromList.R, README.md, tests/testthat/test-chooseFromList.R
- allow to select multiple items like `1:3,6` also as `1-3,6`
- I find that a bit more convenient, in particular on the num block
- method: accept `-` as input, and then simply replace it by `:` before `eval` is executed
=> accept 1-3 just like 1:3 in chooseFromList

.buildlibrary, CITATION.cff, DESCRIPTION, R/getModules.R, R/replace_in_file.R, README.md
- if a module was renamed (as was the case with `29_ageclass` -> `28_ageclass` in MAgPIE) or deleted (as was the case with `30_crop` in MAgPIE), but git does not delete the folder because of some input files lying around, the scripts fails
- See for example REMIND's automated model tests: `/p/projects/remind/modeltests/remind/tests/test-full-2024-07-09.log`:
```
Error: Chosen realization "feb21" does not exist for module "ageclass"
Execution halted
```
- With this PR: in `getModules`, drop folders that do not contain a single `*.gms` file (usually: `module.gms`), and raise a warning instead
- For REMIND, after creating an empty `18_test` folder and executing `Rscript start.R -t`, before and after this PR:
```
Error: Chosen realization "NULL" does not exist for module "test"
```
``` …
```
=> drop empty module subfolders in getModules

.buildlibrary, CITATION.cff, DESCRIPTION, R/setScenario.R, README.md, man/setScenario.Rd
So far it was only possible to pass a path to a `scenario_config.csv` to the function. Now you can also pass a data frame that contains the scenario config.
=> Add option to pass a scenario config as data frame to setScenario()

.buildlibrary, CITATION.cff, DESCRIPTION, R/readDefaultConfig.R, README.md, man/readDefaultConfig.Rd
- Allow to use a different file than `main.gms` as model main file.
- I need that for implementing a test in REMIND.
=> allow to specify main file name in readDefaultConfig

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/download_unpack.R, README.md, man/download_unpack.Rd
So far `stopOnMissing` is a single boolean. This PR introduces the option to provide a vector for `stopOnMissing` that individually defines for each input file whether to warn or stop if the respective file is not found. If `stopOnMissing` has a single element, it applies equally to all input files. This ensures backwards compatibility.
=> Add the option to individually define for each input file whether to warn or stop in case the file is not found.

.buildlibrary, CITATION.cff, DESCRIPTION, R/download_unpack.R, README.md
Print a message only instead of throwing a warning if an *optional* input file is missing.
=> Print a message only instead of throwing a warning

.buildlibrary, CITATION.cff, DESCRIPTION, R/readDeclarations.R, README.md, tests/testthat/test-readDeclarations.R
Without that,
```
sets
empty_set  ""  / /
;
```
would result in the description being read as `"   "`, which is why some empty descriptions in REMIND [went unnoticed](https://github.com/remindmodel/remind/pull/1859/files#diff-aa31f6bfb877de1770c8981ff6318d45727e5d4dc7351f17cb60bc714ed6798c).
Adjust test to show it now works as intended, which will then correctly raise errors in codeCheck
=>  remove blanks in readDeclarations 

.buildlibrary, .github/workflows/check.yaml, CITATION.cff, DESCRIPTION, R/update_modules_embedding.R, README.md, tests/testthat/test-update_modules_embedding.R
This changes `update_module_embedding` to add end patterns (`#+ R SECTION START ...`) for `realization.gms` and `module.gms` in case they are not present. 
While this could be done for other files (`include.gms` and `sets.gms`), I decided against it, as a missing end pattern in these files might indicate a more general problem.
With this change the code snippets in the _Creating a new realization_ tutorial work, otherwise they will fail in the step _Update the code_.
(Depends on #110 )
=> Improves update_module_embedding to handle missing end patterns 
